# This is a basic workflow to help you get started with Actions

name: Pull-Request-Protection

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  grafe-core:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./grafe-core

    strategy:
      matrix:
        node-version: [12.x] 
        # we currently only support 12.x but we will add more late
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm packages for grafe-core
      run: npm ci
    - name: Lint the grafe-core
      run: npm run lint
    - name: Build the grafe-core
      run: npm run build
    - name: Test the grefe-core
      run: npm test
    - name: Generate coverage for grafe-core
      run: npm run coverage --reporter=text
    - name: Check coverage for grafe-core
      run: npm run coverage-check
